SELECT COUNT(CITY) - COUNT(DISTINCT CITY) AS difference FROM STATION;

SELECT CITY, LENGTH(CITY) FROM (SELECT t.CITY FROM STATION t ORDER BY LENGTH(t.CITY), t.CITY FETCH FIRST 1 ROW ONLY) x
UNION ALL
SELECT CITY, LENGTH(CITY) FROM (SELECT t.CITY FROM STATION t ORDER BY LENGTH(t.CITY) DESC, t.CITY FETCH FIRST 1 ROW ONLY) y;

SELECT DISTINCT t.CITY FROM STATION t WHERE t.CITY LIKE 'A%' OR t.CITY LIKE 'E%' OR t.CITY LIKE 'I%' OR t.CITY LIKE 'O%' OR t.CITY LIKE 'U%';


SELECT
    CASE WHEN g.Grade < 8 THEN NULL ELSE s.Name END, g.Grade, s.Marks
FROM Students s JOIN Grades g ON s.Marks BETWEEN g.Min_Mark AND g.Max_Mark
ORDER BY g.Grade DESC,
         CASE WHEN g.Grade >= 8 THEN s.Name END ASC,
         CASE WHEN g.Grade < 8 THEN s.Marks END ASC;

SELECT co.Continent, FLOOR(AVG(ct.Population)) FROM CITY ct JOIN COUNTRY co ON ct.CountryCode = co.Code GROUP BY co.Continent;

SELECT CASE WHEN A + B <= C OR A + C <= B OR B + C <= A THEN 'Not A Triangle' WHEN A = B AND B = C THEN 'Equilateral' WHEN A = B OR B = C OR A = C THEN 'Isosceles' ELSE 'Scalene' END FROM TRIANGLES;
