version: '2.7'

services:
  currency-exchange:
    image: bunty27/smd-currency-exchange-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports: 
      - "8000:8000"
    networks:
      - "nwt1"
    depends_on:
      - naming-server
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka
      #- SPRING.ZIPKIN.BASEURL=http://zipkin-server:9411/
      - MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin-server:9411/api/v2/spans
  
  currency-conversion:
    image: bunty27/smd-currency-conversion-service:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports: 
    - "8100:8100"
    networks:
      - "nwt1"
    depends_on:
      - naming-server
      - currency-exchange
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka
      #- SPRING.ZIPKIN.BASEURL=http://zipkin-server:9411/
      - MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin-server:9411/api/v2/spans
  
  naming-server:
    image: bunty27/smd-naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - "nwt1"
      
  api-gateway:
    image: bunty27/smd-api-gateway:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    networks:
      - "nwt1"
    depends_on:
      - naming-server
    environment:
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://naming-server:8761/eureka
      #- SPRING.ZIPKIN.BASEURL=http://zipkin-server:9411/
      - MANAGEMENT.ZIPKIN.TRACING.ENDPOINT=http://zipkin-server:9411/api/v2/spans
      
  zipkin-server:
    image: openzipkin/zipkin:latest
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - nwt1
    restart: always
    
    ## docker run --rm -it -p 5672:5672 -p 15672:15672 rabbitmq:4.0.0-rc.1-management
  rabbittmq:
    image: rabbitmq:4.0.0-rc.1-management
    ports:
      - "5672:5672"
      - ""
    networks:
      - nwt1
      
networks:
  nwt1: